swagger: '2.0'
info:
  version: 1.1.0
  title: dal-recero-access
  description: ''
host: 'localhost:8080'
basePath: /
tags:
  - name: User
    description: 'User related endpoints'
paths:
  '/api-recero/user/login{num_rut}':
    get:
      summary: Get user information
      operationId: getUserInfo
      tags:
        - User
      produces:
        - application/json
      parameters:
        - name: num_rut
          in: path
          type: string
          required: true
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/response-model-user'
        '401':
          $ref: '#/responses/response-unauthorized'
        '500':
          $ref: '#/responses/response-internal-server-error-500'
  '/api-recero/user/profile{id_perfil}':
    get:
      summary: Get profile information
      operationId: getProfileInfo
      tags:
        - Profile
      produces:
        - application/json
      parameters:
        - name: id_perfil
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/response-model-profile'
        '401':
          $ref: '#/responses/response-unauthorized'
        '500':
          $ref: '#/responses/response-internal-server-error-500'
definitions:
  notification:
    type: object
    properties:
      category:
        description: Category of this notification as a Http status
        type: string
        example: bad request
      code:
        description: Notification code. First character indicates severity (E,W,I).
        type: string
        example: bad request
  model-user:
    type: object
    properties:
      id_login:
        type: integer
        description: "Primary Key from entity login"
        example: 1
      id_perfil:
        type: integer
        description: "Foreign key from entity profile"
        example: 1
      rut_num_usuario:
        type: string
        description: "Digital Number Identification from Chile to rut customer"
        example: "Enterprise DNI 88544647-9 - Natural Person DNI 18278775-1"
      is_valid:
        type: string
        description: "When parameters have data user login it's not available to login, when is empty is allowed"
        example: "2021-03-24 16:48:05.591"
  model-profile:
    type: object
    properties:
      id_perfil:
        type: integer
        description: "foregein key from entity profile"
        example: 1
      descripcion_profile:
        type: string
        description: "description profile"
        example: "Hola soy usuario de recero"
      num_rut_usuario:
        type: string
        description: "foreing key from entity user"
        example: "106665898"
      is_valid:
        type: boolean
        description: "verificacion de usuario"
        example: "true"
      fecha_creacion:
        type: string
        description: "date"
        example: "2021-03-24 16:48:05.591"
      contrasena_perfil:
        type: string
        description: "password for users"
        example: "123abc"
      id_roles:
        type: integer
        description: "foreing key from entity roles"
        example: 1
  response-model-user:
    allOf:
      - $ref: '#/definitions/response-base'
      - type: object
        properties:
          userDetails:
            $ref: '#/definitions/model-user'
  response-model-profile:
    allOf:
      - type: object
        properties:
          profileDetails:
            $ref: '#/definitions/model-profile'
responses:
  response-internal-server-error-500:
    description: Internal Server error
    schema:
      $ref: '#/definitions/notification'
  response-unauthorized:
    description: Authentication information is missing or invalid
    schema:
      $ref: '#/definitions/notification'
    headers:
      WWW_Authenticate:
        type: string